#!/bin/bash
source ./src/core.bash
load_component "status" "measure"

# Setup commonly used vars
TOTAL_SWAP=$(get_system_total_swap)

# Global status or only for task?
if [[ -z "$1" ]]; then
  display_system_status
else
  test -e $TASKS_DIR/$1 && display_task_status $1 || echo -e '\e[1;31mNo such task: '$1'\e[0;0m'
fi
