#!/bin/bash
# Parse params into bash vars
parse_args() {
  for p in "$@"; do
    case $p in
      --status-file=*)
        STATUS_FILE="${p#*=}"
        ;;
      --check-timeout=*)
        CHECK_TIMEOUT="${p#*=}"
        ;;
      --tasks-dir=*)
        TASKS_DIR="${p#*=}"
        ;;
      --work-dir=*)
        WORK_DIR="${p#*=}"
        ;;
      --pid-file=*)
        PID_FILE="${p#*=}"
        ;;
      --log-file=*)
        LOG_FILE="${p#*=}"
        ;;
      --start)
        ARG_START=1
        ;;
      --stop)
        ARG_STOP=1
        ;;
      --reload)
        ARG_RELOAD=1
        ;;
      --restart)
        ARG_RESTART=1
        ;;
      --task-pids)
        ARG_TASK_PIDS=1
        ;;
      --status)
        ARG_STATUS_ALL=1
        ;;
      --status=*)
        ARG_STATUS="${p#*=}"
        ;;
      --colorize)
        COLORIZE=1
        ;;
      --add=*)
        ARG_ADD="${p#*=}"
        ;;
      --edit=*)
        ARG_EDIT="${p#*=}"
        ;;
      --delete=*)
        ARG_DELETE="${p#*=}"
        ;;
      --task-example)
        TASK_EXAMPLE=1
        ;;
      --help|-h)
        HELP=1
        ;;
      *) # unknown option
        ;;
    esac
  done
}
